styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  shellcheck:
    enabled: true
  remark-lint:
    enabled: true
pull_requests:
  comments: false
exclude_paths:
- config
- priv/repo
- test
