defmodule HELL.IPv6Test do
  use ExUnit.Case

  alias HELL.TestHelper.Random
  alias HELL.TestHelper.IP
  alias HELL.IPv6

  describe "generate/1" do
    test "includes the header" do
      assert "3456:" <> _ = IPv6.generate([0x3456])
      assert "ef01:3456:" <> _ = IPv6.generate([0xef01, 0x3456])
      assert "abcd:ef01:3456:" <> _ = IPv6.generate([0xabcd, 0xef01, 0x3456])
      assert "abcd:ef:3:" <> _ = IPv6.generate([0xabcd, 0xef, 0x3])
      assert "abcd:0:abcd:" <> _ = IPv6.generate([0xabcd, 0x0, 0xabcd])
    end

    test "autogenerated IPs are valid" do
      Random.repeat fn ->
         header = Random.repeat(fn -> Random.number(0..0xffff) end, min: 1, max: 3)
         ip = IPv6.generate(header)
         assert IP.ipv6?(ip)
      end
    end

    test "fills empty groups with 0 " do
      assert "5fce:0:0:" <> _ = IPv6.generate([0x5fce])
      assert "5fce:abc:0:" <> _ = IPv6.generate([0x5fce, 0xabc])
    end
  end
end